### ISSUE TITLE
feature request: copy fields from one tag to another

### ISSUE THREAD

**Issue by sharethewisdom** [muennich/id3ted#12]
Involved persons frames are often not used correctly. I had files with names of original composers in the TPE1 (main artist) frame, and copied them over to TCOM:

``` sh
for f in *.mp3; do id3ted -l "$f"|grep TPE1|sed 's/^TPE1:\s//'|tr -d '\n'|xargs -0I '{}' id3ted --TCOM '{}' "$f"; done
```

but I think it could be useful to have duplication implemented one way or another

**Comment by xyb3rt** [comment]
Sorry for replying this late. I will only fix issues but do not implement new features as I simply do not have the time to do so. I also do not think that this feature is really required as you have already found an elegent way to achieve the same thing with a much more flexible shell script.
